name: Deploy to VM Broo

on:
  push:
    branches:
      - master  # Adjust this to your deployment branch

jobs:
  build-and-upload-to-docker-hub:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: indrafajar/index-be:latest  # Update this

  deploy-vm:
    runs-on: ubuntu-latest
    needs: build-and-upload-to-docker-hub
    steps:
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.VM_SSH_KEY }}
      - name: Deploy to VM
        env:
          HOST: ${{ secrets.VM_HOST }}
          USER: ${{ secrets.VM_USERNAME }}
          PORT: ${{ secrets.VM_PORT }}
        run: |
          ssh -o StrictHostKeyChecking=no -p $PORT $USER@$HOST '
            set -e
            docker pull indrafajar/index-be:latest
            if [ "$(docker ps -a -q -f name=index-be-run)" ]; then
              if [ "$(docker ps -q -f name=index-be-run)" ]; then
                docker stop index-be-run
              fi
              docker rm index-be-run
            fi
            docker run -d --name index-be-run --restart unless-stopped --network my-app -p 3100:3000 indrafajar/index-be:latest
            docker cp ~/index-be/.env index-be-run:/app/
            docker restart index-be-run
            docker image prune -f
          '
